"""empty message

Revision ID: 725c171c8d4e
Revises: 
Create Date: 2020-07-12 02:41:33.990889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "725c171c8d4e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("genre", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_genre"), "categories", ["genre"], unique=True)
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("director", sa.String(length=64), nullable=True),
        sa.Column("year", sa.String(length=4), nullable=True),
        sa.Column("title", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "movie_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("movie_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_purchased", sa.DateTime(), nullable=True),
        sa.Column("paid", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("movie_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_date_purchased"), "orders", ["date_purchased"], unique=False
    )
    op.create_index(op.f("ix_orders_paid"), "orders", ["paid"], unique=False)
    op.create_table(
        "user_movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("movie_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_movies")
    op.drop_index(op.f("ix_orders_paid"), table_name="orders")
    op.drop_index(op.f("ix_orders_date_purchased"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("movie_categories")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("movies")
    op.drop_index(op.f("ix_categories_genre"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
